# Project information
site_name: Shaazzz Guide
site_url: https://sohsoh84.github.io/Shaazzz-Guide/
site_author: Shaazzz
site_description: Shaazzz Guide
# Repository
repo_name: sohsoh84/Shaazzz-Guide
repo_url: https://github.com/sohsoh84/Shaazzz-Guide

# Copyright
copyright: |
  تمامی مطالب این وب‌سایت تحت پروانه
  <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" style="color: #4ab6f1">CC-BY-SA</a>
  در دسترس است.

# Configuration
theme:
  name: material
  custom_dir: material/.overrides
  features:
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Vazirmatn
    code: Source Code Pro
  logo: "https://raw.githubusercontent.com/shaazzz/site/main/docs/assets/images/sid.png"
  favicon: "https://raw.githubusercontent.com/shaazzz/site/main/docs/assets/images/sid.png"

# Plugins
plugins:
  - search

  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: material/web
      link: https://shaazzz.ir
      name: وب‌سایت
    - icon: fontawesome/brands/github
      link: https://github.com/shaazzz
      name: گیت‌هاب
    - icon: fontawesome/brands/telegram
      link: https://t.me/shaazzz
      name: تلگرام

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
